### ISSUE TITLE
NuGet Package

### ISSUE THREAD

**Issue by Alfetta159** [mmkiwi/MdbReader#2]
When will there be a NuGet package? Let me know if you would like a pull request.

I find this to be a more than sufficient product for what I need. I forked it mainly because I wanted a NuGet package, but I don't think just that is warranted for just packaging, so I will kill that as long as we can get a NuGet package.

tl;dr
Thank you for this repo, I have been going crazy trying to find an easy want to get an Azure hosted function to parse an old MDB (version) file w/o OleDB. Latest versions of Access won't even open it.

**Comment by mmkiwi** [comment]
@Alfetta159 I can definitely make a nuget package for this. 

It's still pretty beta-quality, and I can't get OLE fields to work right, but I'm glad it's helpful. I had a pretty similar situation where I had to interface with a program that outputted old JET3 databases. I managed to get it working enough for my use cases so I never finished it all the way but now that I know it's useful for other folks I might dive back in.

**Comment by mmkiwi** [comment]
@Alfetta159 published the package to Nuget as [MMKiwi.MdbReader]https://www.nuget.org/packages/MMKiwi.MdbReader/0.1.0-beta1)

Like I said before, super beta quality so I'd be careful before using it in production, but I'm glad it's helpful!
